server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000

  client:
    url: ${CLIENT_URL:http://localhost:4200}

spring:
  application:
    name: API-GATEWAY

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  codec:
    max-in-memory-size: 10MB

  cloud:
    gateway:
      routes:

        # ================= AUTH SERVICE =================
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: admin-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter
        # ================= RESUME SERVICE =================
        - id: resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/api/v1/resumes/**
          filters:
            - AuthenticationFilter
        # ================= RESUME SECTION SERVICE =================
        - id: resume-section-service
          uri: lb://RESUME-SECTION-SERVICE
          predicates:
            - Path=/api/v1/sections/**
          filters:
            - AuthenticationFilter
        # ================= AI-SERVICE =================
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - AuthenticationFilter
        # ================= TEMPLATES-SERVICE =================
        - id: template-service
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/api/v1/templates/**
#          filters:
#            - AuthenticationFilter
        # ================= PAYMENT-SERVICE =================
        # 1. PUBLIC CALLBACKS (No Filter)
        - id: payment-callback-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/pay/success, /api/v1/payments/pay/cancel

        # 2. SECURE ENDPOINTS (Has Filter)
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter
        # ================= EXPORT-SERVICE =================
        - id: export-service
          uri: lb://EXPORT-SERVICE
          predicates:
            - Path=/api/v1/exports/**
          filters:
            - AuthenticationFilter
        - id: export-download-service
          uri: lb://EXPORT-SERVICE
          predicates:
            - Path=/api/v1/export/**
          filters:
            - AuthenticationFilter
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
# OPTIONAL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
