server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # ================= AUTH SERVICE =================
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        # ================= RESUME SERVICE =================
        - id: resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/api/v1/resumes/**
          filters:
            - AuthenticationFilter
        # ================= RESUME SECTION SERVICE =================
        - id: resume-section-service
          uri: lb://RESUME-SECTION-SERVICE
          predicates:
            - Path=/api/v1/sections/**
          filters:
            - AuthenticationFilter
        # ================= AI-SERVICE =================
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - AuthenticationFilter
        # ================= TEMPLATES-SERVICE =================
        - id: template-service
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - AuthenticationFilter
        # ================= PAYMENT-SERVICE =================
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# OPTIONAL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}